### ISSUE TITLE
We need an Core Library badge

### ISSUE THREAD

**Issue by joshgoebel** [Arduboy/Arduboy#104]
Reference: 

http://marabesi.com/wp-content/uploads/2015/06/badges2.png

We need a badge that authors using ONLY properly linked external libraries can add to their readmes so users know the software will compile properly with core library.  Libs that insist on bundling everything themselves wouldn't be eligible for the badge.

Thoughts?

**Comment by joshgoebel** [comment]
Like:

Hardware
![](https://img.shields.io/badge/Production_1.0-yes-green.svg)  ![](https://img.shields.io/badge/DevKit-no-red.svg) 
Libraries
![](https://img.shields.io/badge/External_Linking-yes-green.svg) ![](https://img.shields.io/badge/Arduboy-1.1-yellow.svg) ![](https://img.shields.io/badge/ArduboyTunes-1.1-yellow.svg) ![](https://img.shields.io/badge/ArduboyExtra-0.9-yellow.svg)

**Comment by MLXXXp** [comment]
:+1:

**Comment by joshgoebel** [comment]
I started using these here:

http://community.arduboy.com/t/official-game-list-for-the-arduboy/783
