### ISSUE TITLE
Do development on a branch?

### ISSUE THREAD

**Issue by MLXXXp** [Arduboy/Arduboy#117]
I think it would be a good idea to create branches for development work and keep _master_ at the latest tagged release. This way, users grabbing _master_ will (hopefully) always get a stable, documented version of the library, equivalent to what the IDE Library Manager will provide.

The branches could be called _development_x_x_, where _x_x_ is the next expected release number _x.x_

Once we're ready to do a new tagged release, we merge to _master_ and tag it. Then, immediately create a new development branch for new work.

**Comment by joshgoebel** [comment]
Master is the development branch, releases are tagged and easily accessible for those wishing to use a release.  Most users should get the library from the IDE, if they are using the repository directly then they're game for pre-release code (or they can of course use any tag they desire).

**Comment by joshgoebel** [comment]
It was considered to tag a 'stable' but that really just duplicates the release versions, which are pretty clear in and of themselves.

**Comment by joshgoebel** [comment]
I created a stable branch for now since we only have a single major release series (1.x).

**Comment by Jezzamonn** [comment]
Just posting that I'm for the idea of the master being the latest stable release. This seems to be the standard for a lot of projects!

**Comment by joshgoebel** [comment]
> This seems to be the standard for a lot of projects!

If you say so.  The projects I use (mostly Ruby though) all typically use master for development and then tag releases.  Since we do have release channels (zipfile, Arduino IDE,etc.) I'm not sure the harm in master being development here.

People SHOULD use the development branch and if they want to use stable they should know why and know how to switch branches.  

This is made more annoying though by the fast that for some reason we're scared to death of finally releasing 1.2

**Comment by MLXXXp** [comment]
> People SHOULD use the development branch and if they want to use stable they should know why and know how to switch branches.

The problem is, many Arduboy developers are beginners. They find the repository, muddle through figuring out how to grab and install the _master_ branch into the IDE (probably not even knowing that other branches exist), and then develop a sketch using it, with reference to the examples, which have been updated to work with the new API. They then make the code available and announce it on the forum.

Next, users who have followed the Quick Start Guide, and have installed the released version of the library, and have no coding experience whatsoever, start posting things like: _I get errors when I try to compile your sketch:_

```
sketch/Utils.h:4:24: fatal error: ab_printer.h: No such file or directory
#include "ab_printer.h"
^
compilation terminated.
```

This has happened numerous times in the forum.

You expect everyone to be an expert or stay away. That's not the philosophy of the Arduboy world. We try to make things as idiot proof as possible.
