### ISSUE TITLE
Should version 1.2 be 2.0?

### ISSUE THREAD

**Issue by MLXXXp** [Arduboy/Arduboy#119]
The current library implements some fairly significant API changes (removal of audio and print functions) that make it non-backwards compatible, and will require many sketches to be modified to get them working again.

I wonder if it would be a good idea to bump up the major version number and call it 2.0.0 instead of 1.2.0? This makes an easy to remember delimiter for the point at which "lots of sketches broke".

**Comment by joshgoebel** [comment]
No, it's not a 2.0.  It only moves a few things around.  Breaking yes... 2.0, no.
