### ISSUE TITLE
Document units such as duration

### ISSUE THREAD

**Issue by joho** [Arduboy/Arduboy#143]
`void ArduboyTunes::tone(unsigned int frequency, unsigned long duration)`

I've no idea what unit I should be specifying duration in. Seconds? Milliseconds? Would be great if those could be included in comments in the header, or even in the argument name `durationInMs` or something.

**Comment by MLXXXp** [comment]
I guess since it's meant to replace [Arduino tone() ](https://www.arduino.cc/en/Reference/Tone) it was assumed that it would be understood that it's in milliseconds.

Your point is noted, though.

**Comment by joho** [comment]
Right. Sorry, I had no idea. Thanks. Arduboy's my first foray into arduino, there's a little bit of a learning curve :)

**Comment by joshgoebel** [comment]
durationInMs isn't the worst idea
