### ISSUE TITLE
Should the new draw() function be simplified and renamed?

### ISSUE THREAD

**Issue by MLXXXp** [Arduboy/Arduboy#146]
I don't really see much of a point for having the new _draw()_ function, which was added in the _develop_ branch. It just saves you from directly calling _clear()_ and _display()_. As with _nextFrame()_, you still have to call it continually until it indicates that it's time for the next frame. I think it would be better if it waited until the next frame time before returning, and I don't think it needs to return any kind of status.

Also, all the other functions that are prefixed with _draw_ only manipulate the screen buffer in RAM. They don't actually change what's displayed on the screen itself. Therefore, I think the name _draw()_ is confusing. Perhaps _render()_ or _renderFrame()_ would be more meaningful. Using the name _renderFrame()_ makes it clearer that it is part of the timed _frame_ functions.

I propose that the function be:

``` cpp
void ArduboyBase::renderFrame(void (*f)())
{
  while (!newFrame()) { } //(!nextFrame() if my "newFrame()" pull request isn't accepted)
  clear();
  (*f)(); // call the function passed as paramter to draw
  display();
}
```

A sketch might then contain

``` cpp
void setup()
{
  arduboy.begin();
  arduboy.setFrameRate(30);
}

void loop()
{
  arduboy.renderFrame(gameFrame);
}

void gameFrame()
{
  // code to update the screen buffer with the next frame contents
}
```

**Comment by shogerr** [comment]
I agree, and in the develop  a `perform()` function that can be passed a pointer to a function has been included. 

The notion of a "draw" routine, the original name, that performs anything from print to poll input is probably the wrong approach. However, a set of handlers for this sort of thing, like a `draw`, `event`, `joystick`, etc. is plausible.

The verb _perform_ seems to capture the idea, that is: "Arduboy, perform _this_", where _this_ is a routine (keeping in mind `do` is a reserved keyword :cry:), but another verb might work better. 

It would be nice to do everything that "begin" does in a constructor perhaps, that would reduce the number of calls a user is required to make.

https://github.com/Arduboy/Arduboy/blob/develop/examples/PerformExample/PerformExample.ino

``` cpp
/**
 * @file DrawExample.ino
 * \brief Implements a test of the draw routine from the ArduboyBase class.
 */

#include <Arduboy.h>

// make an instance of arduboy used for many functions
Arduboy arduboy;

void setup() {
  arduboy.begin();
  arduboy.setFrameRate(15);
}

void loop() {
  // perform the action() function specified below.
  arduboy.perform(action);
}

// function to pass to the Arduboy perform routine in loop()
void action() {
  arduboy.setCursor(4, 9);
  arduboy.print(F("Hello, world!"));
}
```

**Comment by MLXXXp** [comment]
Although I understand the intention, upon further consideration I don't think the _perform()_ function should be added to the Arduboy library. My reasons are as follows:
1. It's a bit higher level than other functions in the library provide and it's only one of many techniques that could be used to implement a control loop. I don't think this library should be dictating only one method.
2. With the combined _display()_ and _clear()_ functionality, _perform()_ is only 3 lines of code. It's easy enough to just add as a separate function in the sketch itself.
3. What if someone wants to use this method, but doesn't want the buffer to be cleared? They wouldn't be able to use this function and would have to have something similar in the sketch itself. There are just too many variations on the theme to have only one in the library.
4. "Experts" wanting to optimise for speed and code size wouldn't use this function. It would likely create more code than other methods, and passing a function as a parameter isn't very efficient.
5. For "beginners", the concept of passing a function as a parameter is quite advanced and could be confusing. Wrapping it up in a "magic" function within the library doesn't provide a learning opportunity as much as an example sketch with _perfom()_ included and well documented as a local function would.

@rogosher If you feel that the method that _perform()_ provides is a good one (and that could be debated since personally, to date, I haven't come across a single Arduboy sketch that uses it), you could still include the _PerformExample_ sketch in the _examples_ directory, but make _perform()_ a well documented local function within the sketch.

**Comment by joshgoebel** [comment]
Think this was the right call. :)

**Comment by MLXXXp** [comment]
@yyyc514 You can close this issue if you like
(you're still a collaborator, aren't you?)
