### ISSUE TITLE
Readme GiF

### ISSUE THREAD

**Issue by eagleanurag** [Arduboy/Arduboy#159]
Hi!
It would be very nice adding some Action Buttons as well as some good looking Gif from the game cosole itslef.

![arduboyplay](https://user-images.githubusercontent.com/22770735/90885129-a0470b00-e3ce-11ea-8412-67df66883dda.gif)

**Comment by MLXXXp** [comment]
Development has ceased on this library. It is no longer being maintained. New programs for the Arduboy should use the [Arduboy2 Library](https://github.com/MLXXXp/Arduboy2).
