### ISSUE TITLE
[size] Figure out how to remove drawRect calls from drawChar

### ISSUE THREAD

**Issue by joshgoebel** [Arduboy/Arduboy#18]
These get compiled in and waste space for anyone not using enlarged font sizes. This uses 216 bytes extra just to compile in drawRect and all it's dependencies when it's never used.

Not sure about the best fix here, but open to suggestion.

**Comment by joshgoebel** [comment]
Funny as it looks you can save 100+ bytes by removing all the special casing between drawing different sizes:

```
    for (int8_t j = 0; j<8; j++)
    {
      draw_color = (line & 0x1) ? color : bg;

      if (draw_color || draw_bg) {
        for (uint8_t a=0; a < size; a++ )
          for (uint8_t b=0; b < size; b++ )
            drawPixel(x+(i*size)+a, y+(j*size)+a, draw_color);
      }

      line >>= 1;
    }
```

The loops just short circuit when size==1 and draw a 1px box instead of larger.  Neither the before or after approach will win any speed awards, so I think the flash savings would be a good inw.

**Comment by joshgoebel** [comment]
Objections?

**Comment by joshgoebel** [comment]
Ping.

**Comment by shogerr** [comment]
How does it change the look between font sizes?

**Comment by joshgoebel** [comment]
It doesn't change the look.

**Comment by joshgoebel** [comment]
Creating PR, closing.
