### ISSUE TITLE
[speed] Bump SPI clock speed to /2 vs /4

### ISSUE THREAD

**Issue by joshgoebel** [Arduboy/Arduboy#27]
This is done like so:

```
SPI.setClockDivider(SPI_CLOCK_DIV2);
```

I'm thinking this should be the default in the core lib.  It reduces the wait time spent doing nothing but waiting on the SPI bus to repaint the screen.  If the final production version is going to run at 8Mhz we definitely want to do this - just to preserve the current SPI speed.  16/4 = 8/2.

I don't have hard #s right this second but in my testing this reduced CPU % for a blank render loop by around 5-10%.  Surprised?  I was surprised that a blank render loop is so slow.  If all you do is use nextFrame at 60FPS and call `clear; print(cpuLoad()); display` out of the box you're talking 31% CPU usage.

With this change and a few others I got that down to 18%.

Thoughts, objections?  If this is good I can do the work and submit a PR.

**Comment by joshgoebel** [comment]
This is also super important if anyone wants to further hack on grayscale stuff... there is a huge diff in vsync if you are at /2 or /4 SPI clock speed.

**Comment by joshgoebel** [comment]
Timing a call to `display()` with micros():

SPI /4 SPI.transfer(): 3700 micros
SPI /2 SPI.transfer(): 2670 micros
SPI /2 hand-optimized loop (tight as it can get): 1170 micros

This might have implications for greyscale.  This is over twice as fast as the previous speed I played with.

**Comment by joshgoebel** [comment]
@ace-dent You asked for hard numbers, there ya go.

**Comment by shogerr** [comment]
This would be a good PR for a development branch.

**Comment by joshgoebel** [comment]
This compiles and works perfectly. I'm not sure why we wouldn't merge it.

**Comment by joshgoebel** [comment]
So looks like this already got merged.
