### ISSUE TITLE
Tunes stuff should be optional, not required

### ISSUE THREAD

**Issue by joshgoebel** [Arduboy/Arduboy#28]
Someone should be able to not use the very expensive and memory heavy Tunes stuff if they don't want to or if they need the space for a more ambitious program.  It probably should not be compiled and linked by default if someone does not use the functionality.

**Comment by shogerr** [comment]
Can we setup something to hook into the compiler settings?

**Comment by joshgoebel** [comment]
Resolved by:
https://github.com/Arduboy/Arduboy/issues/102
