### ISSUE TITLE
not_pressed() should be notPressed() and start() should be begin()

### ISSUE THREAD

**Issue by MLXXXp** [Arduboy/Arduboy#51]
Currently there is a function named _not_pressed()_, for testing the state of pressed buttons. In keeping with the [Arduino Style Guide for Writing Libraries](https://www.arduino.cc/en/Reference/APIStyleGuide), which recommends using [CamelCase](https://en.wikipedia.org/wiki/CamelCase) instead of underscores in function names, this should be changed to _notPressed()_.

Hopefully not too many sketches have used this function yet, so it's best to change it as soon as possible to minimise the impact.

The style guide also states:

> Use begin() to initialize a library instance, usually with some settings. Use end() to stop it.

so _start()_ should be _begin()_. This one would be harder to change since practically every existing sketch will be using it. Perhaps we could add _begin()_ as a synonym of _start()_. All new sketches should use _begin()_ and _start()_ could be depreciated once all old sketches had been changed.

**Comment by MLXXXp** [comment]
If _not_pressed()_ does get changed to _notPressed()_ it should be added to _keywords.txt_. I didn't put _not_pressed()_ in _keywords.txt_ on the assumption that it would be changed.

**Comment by joshgoebel** [comment]
We can change to begin() now and just tag start with the depreciated attribute (I think)...  notPressed is good change, and more C like I think... I probably did that wrong because I'm thinking in Ruby speak, where underscores is more common. ;-)

Though actually perhaps we should just make someone do `!pressed()` and remove `notPressed` completely.   The more I think about it the sillier it sounds.

**Comment by MLXXXp** [comment]
> Though actually perhaps we should just make someone do !pressed() and remove notPressed completely.

The way the functions are written, _!pressed()_ is not equivalent to _notPressed()_. When more than one button is specified, they each serve a different useful purpose. _pressed()_ checks if the buttons specified in the argument, as a bit mask, are **all** currently **pressed**. _notPressed()_ checks if the buttons specified in the argument are **all** currently **released**.

`notPressed(LEFT_BUTTON + UP_BUTTON)` will only return _true_ if **both** the _left_ button and the _up_ button are not being pressed. i.e. All of the specified buttons must be in a released state.

`!pressed(LEFT_BUTTON + UP_BUTTON)` will return _true_ if **either** the _left_ button **or** the _up_ button is not being pressed (or both). i.e. Only one of the specified buttons (at least) needs to be in a released state.

**Comment by MLXXXp** [comment]
> We can change to begin() now and just tag start with the depreciated attribute (I think)

Yes, it looks like we can use a _deprecated_ (not _depreciated_; my bad) attribute on the _start()_ function. Although it just generates a warning, which will likely not be seen or be ignored by most sketch developers, it can't hurt.

In _Arduboy.h_, I changed

``` cpp
  void start();
```

to

``` cpp
  void start() __attribute__ ((deprecated));
```

This produced a warning, when a sketch was compiled, similar to:

```
test.ino: In function 'void setup()':
test.ino:8:14: warning: 'void Arduboy::start()' is deprecated (declared at Arduino/libraries/Arduboy/Arduboy.h:48) [-Wdeprecated-declarations]
   aboy.start();
              ^
```

So we could change _start()_ to _begin()_ then add the _deprecated_ attribute to _start()_ and have _start()_ just call _begin()_.

Note: I tried using the _alias_ attribute to make _start()_ an alias of _begin()_ but I couldn't get it to work. If it can be done, the syntax escapes me.

**Comment by joshgoebel** [comment]
> . The way the functions are written, !pressed() is not equivalent to notPressed().

I know, I wrote them, but is this super useful behavior that people couldn't just code themselves?

**Comment by joshgoebel** [comment]
> So we could change start() to begin() then add the deprecated attribute to start() and have start() just call begin().

Yes, deprecated start would just call begin.  Exactly.

**Comment by MLXXXp** [comment]
> I know, I wrote them, but is this super useful behavior that people couldn't just code themselves?

Are you asking if we should keep _pressed()_ but remove _notPressed()_? Unless you think we should eliminate both and have developers just implement the desired equivalents themselves using _getInput()_, then I say keep them both.

I used both _pressed()_ and _notPressed()_ in my [ArduboyLife](https://github.com/MLXXXp/ArduboyLife) sketch. _notPressed()_ was used to wait for a pair of buttons to both be released. In my case, I could probably have used `getInput() == 0` but that wouldn't have worked if I'd wanted to ignore other buttons that were still held, and I think _notPressed()_ reads a bit better if _pressed()_ has previously been used.

**Comment by joshgoebel** [comment]
Ok, lets just rename it then.

**Comment by joshgoebel** [comment]
See my example: https://github.com/Arduboy/Arduboy/pull/60

**Comment by joshgoebel** [comment]
Do you think begin needs to extend to the helper classes like audio?  Currently uses `setup`.  If so lets changes that also.  That should (at this point) really just be an internal only change so we don't need to deprecate the old call.

**Comment by MLXXXp** [comment]
What about _ArduboyCore::setup()_? Is it needed? I don't think it's used.

**Comment by joshgoebel** [comment]
No, the idea was you'd use that if you wanted to use core all on it's own, but it's probably way more likely you'd be subclassing from core and just calling boot()... and core is really super low-level, so I don't think it needs a begin - I don't think we should encourage people to use it that way.

So yeah I think we could remove setup() if you want.

**Comment by joshgoebel** [comment]
Was hoping to roll 0.9 today - think you'll have anytime to get to this?

**Comment by MLXXXp** [comment]
I'm planning to do it in the next few hours.

**Comment by MLXXXp** [comment]
Pull request #67 created. Closing this issue.
