### ISSUE TITLE
Setting RGB LEDs can interfere with tunes

### ISSUE THREAD

**Issue by joshgoebel** [Arduboy/Arduboy#64]
The conflict is Timer 1 Compare A.

Temp workaround:
Do not use both RGB led and music.

**Comment by joshgoebel** [comment]
This needs to be moved to the new Tunes repository - or does it stay here?  It's not really any problem with PWM or RGB, so I think it needs to move, yes?

**Comment by MLXXXp** [comment]
Yes, move it.

**Comment by joshgoebel** [comment]
Moved. Closing.
