### ISSUE TITLE
FloatyBall or FlappyBall?

### ISSUE THREAD

**Issue by MLXXXp** [Arduboy/Arduboy#70]
Just an observation:
The example sketch is named _FloatyBall_ but the intro screen says _FlappyBall_.

**Comment by MLXXXp** [comment]
Also, we may want to get rid of the little _ARDUINO_ logo that's displayed on start up, especially if there's going to be an automatic _Arduboy_ logo.

**Comment by MLXXXp** [comment]
Actually, I think this game should be removed unless it's tuned a bit. At the speed the ball rises and falls, I find it virtually unplayable.

**Comment by shogerr** [comment]
It's not exactly a shining beacon of programming magnificence, but people do play it/ask for it.

I can fix those two issues, if we get the bootscreen included, the Arduboy logo can come out, thanks :+1:

**Comment by joshgoebel** [comment]
I put it under proper frame management (at 30 FPS as it was designed for) but man you're right it's unplayable. :-)

**Comment by joshgoebel** [comment]
To clean it up you'd make the bird a bitmapped sprite with animation frames and bump this to 60 FPS and then adjust the physics.  You could also have really nice bitmaps for the columns vs them being simple rects.  Lots of opportunity here once you fixed the physics.

**Comment by shogerr** [comment]
This was discussed a bit with @bateske, and we can just take out flappy bird. It will probably be easily found on codebender etc in the future. Or an arduboy-extras repo.
