### ISSUE TITLE
Compile warnings due to always_inline attribute

### ISSUE THREAD

**Issue by MLXXXp** [Arduboy/Arduboy#71]
The library generates three compile warnings due to using the _always_inline_ attribute.

```
core.cpp:145:6: warning: always_inline function might not be inlinable [-Wattributes]
 void ArduboyCore::safeMode()
      ^
core.cpp:112:6: warning: always_inline function might not be inlinable []
 void ArduboyCore::bootLCD()
      ^
core.cpp:93:6: warning: always_inline function might not be inlinable [-Wattributes]
 void ArduboyCore::bootPins()
      ^
```

I don't like to see compiler warnings. It make me wonder if it might be more serious than just a warning, such as what I described in pull request #69. Is there something that can be changed to eliminate these warnings?

If you feel that the code is correct and the warnings can be ignored, via a quick search I found a possible solution using pragmas .  Example ([described here](http://stackoverflow.com/questions/3378560/how-to-disable-gcc-warnings-for-a-few-lines-of-code)):

``` c
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-result"
    write(foo, bar, baz);
#pragma GCC diagnostic pop
```

I tried it, using _-Wattributes_ and containing the entire function, and it worked.

**Comment by shogerr** [comment]
I think we might also look at this [example](http://stackoverflow.com/questions/32432596/warning-always-inline-function-might-not-be-inlinable-wattributes).

See the bottom reply.

It would be nice to squelch any warnings before an end-user starts using, but I dont think this is more than the compiler having issues with something being used inline when it hasn't been explicitly told to do so, or not to care. Suppressing this warning does not appear to be a problem. Let's see if Dreamer can weigh in.

**Comment by joshgoebel** [comment]
I'll look into this, but it's 'causing no harm - and it is doing what it's intended to - inline methods that are never meant to be called outside the init sequence - saving space in flash.

**Comment by joshgoebel** [comment]
Ref: https://github.com/Arduboy/Arduboy/pull/72

**Comment by joshgoebel** [comment]
If there is some problem with my PR and it's not fixable any other way then I suggest we try `#pragma GCC diagnostic ignored`.  I should point out that I think the default is for the compiler not to even show warnings though.  Mine was turned off and I had to turn it on manually at least.

**Comment by joshgoebel** [comment]
Closing to reopen if PR is inadequate.

**Comment by MLXXXp** [comment]
> I should point out that I think the default is for the compiler not to even show warnings though.

There's a setting in the IDE under _File -> Preferences_ in the _Settings_ tab:
_Show verbose output during:_ (with check boxes for _compilation_ and _upload_)

Setting it for compilation will show the warnings, which is how I like it set, especially when developing code. When I see orange lines flash by, I go back and check to see if it's something I caused.

**Comment by shogerr** [comment]
Thanks @MLXXXp thats a good inclusion for the issue, I didn't know about that setting. Ill admit, I'm the atypical user using a makefile to build the arduboy programs when its for personal use.
