### ISSUE TITLE
Control of TXLED and RXLED

### ISSUE THREAD

**Issue by MLXXXp** [Arduboy/Arduboy#76]
It looks like the production Arduboy has both a TXLED and RXLED wired on the same pins as the Arduino Leonardo, Micro and Pro Micro (and likely others). Therefore, I assume the Arduboy's  _pins_arduino.h_ file will include the definitions for controlling these LEDs as others do. E.g.

``` cpp
#define TX_RX_LED_INIT  DDRD |= (1<<5), DDRB |= (1<<0)
#define TXLED0          PORTD |= (1<<5)
#define TXLED1          PORTD &= ~(1<<5)
#define RXLED0          PORTB |= (1<<0)
#define RXLED1          PORTB &= ~(1<<0)
```

``` cpp
#define LED_BUILTIN_RX 17
#define LED_BUILTIN_TX 30
```

For reference: [Example 1: Blinkies!](https://learn.sparkfun.com/tutorials/pro-micro--fio-v3-hookup-guide/example-1-blinkies)

Is this adequate to allow a sketch to control these LEDs or should we include library functions to make it easier?

Note that the RXLED is on the same pin as the DevKit's LED.

**Comment by MLXXXp** [comment]
> For reference: [Example 1: Blinkies!](https://learn.sparkfun.com/tutorials/pro-micro--fio-v3-hookup-guide/example-1-blinkies)

Note that, contrary to that article, you can control TXLED as digital Pin 30 (like RXLED is Pin 17). And there are `#define LED_BUILTIN_RX 17` and `#define LED_BUILTIN_TX 30` available. I think this was added in Arduino version 1.5+

**Comment by joshgoebel** [comment]
What file are these in?  I didn't see them when I looked.  I think eventually we should have a nice API wrapper so we can hard code the PORTS and bit stuff rather than people using digitialWrite (which is super expensive).

I was planning on getting to it but hadn't decided an API yet... one method, two?  Boolean?  They aren't hardware PWMable.

**Comment by MLXXXp** [comment]
> What file are these in?

The file is _pins_arduino.h_ which is located in a subdirectory of the _variants_ directory for the board that you are using. The _variants_ directory is somewhere under a _hardware_ directory. The location of _hardware_ differs depending on whether it's an official Arduino installed as part of the IDE or a third party board installed as an add-on. The locations are probably also dependent on the host O/S.

**Comment by joshgoebel** [comment]
I'm very familiar with that file... it's a trusted companion... but I must have missed the TX/RX stuff... looking again now.

**Comment by joshgoebel** [comment]
Guess I didn't look very hard. :)

**Comment by joshgoebel** [comment]
```
    void setRGBled(uint8_t red, uint8_t green, uint8_t blue); // already coded
    void setRXled(bool on);
    void setTXled(bool on);
```

And we just wrap those defines nicely with an API.  Thoughts?

**Comment by MLXXXp** [comment]
The [_Arduino Style Guide for Writing Libraries_](https://www.arduino.cc/en/Reference/APIStyleGuide) states:

> Use read() to read inputs, and write() to write to outputs, e.g. digitalRead(), analogWrite(), etc.

Which would mean using _write_ instead of _set_.

``` cpp
void writeRGBled(uint8_t red, uint8_t green, uint8_t blue); // already coded
void writeRXled(bool onoff);
void writeTXled(bool onoff);
```

Or the more compliant postfix instead of prefix: _RGBledWrite()_, etc.?

And should we provide complimentary _read_ functions?

And if we decide on this, then maybe _readButtonState()_ or _readButtonStatus()_  (or the postfix versions) instead of the _pollButtonState()_ or _pollButtonStatus()_ that you are proposing in issue #78, in place of _getInput()_.

Strangely, the guide says later:

> **Try to avoid boolean arguments.** Instead, consider providing two different functions with names the describe the differences between them.

But maybe that refers to functions with multiple parameters?? Or non-I/O related functions??

**Comment by joshgoebel** [comment]
> Or the more compliant postfix instead of prefix: RGBledWrite(), etc.?

I don't see where it mandates the order. And pins are inputs and outputs, lights are lights.  They can be wired to pins yes, but those low level functions are for working with pins - and the concepts are named accordingly.  We don't write to the arduboy screen, we draw to it... higher level gets to name things higher level. :-)

> And should we provide complimentary read functions?

I don't think that's necessary, if someone wants to do crazy animation or a tight loop that should probably be tracking the status themselves in a counter, not polling for it each time.  Plus RGB isn't an input that you can just poll... I'm pretty sure you could get those numbers back by reading the IO counter ports and inverting, but it's not analogous to analogRead() or anything - it's a whole other thing.

I think you could argue the boolean thing both ways. If you're doing that though you're not really "writing" anything anymore (even at the function level)... write(true) is maybe writing something... TXon() and TXoff() is just state toggling... I wouldn't call it `writeTXon` or `TXonWrite`, that's just silly.

So what about:

```
  ledTXon(); 
  ledRXoff();
  // ...

```

**Comment by joshgoebel** [comment]
And lets remember it's a guide, not a Bible. :)

**Comment by joshgoebel** [comment]
```
void writeRGBled(
```

While you might write the red inverse duty value, write the green inverse duty value, and write the blue inverse duty value when you do them all together now you're doing a new thing.  You're setting a color, a much higher level concept. :-)

I also like `setRGBcolor(r,g,b)`.

**Comment by MLXXXp** [comment]
> And pins are inputs and outputs, lights are lights.

So what type of things do you think the guide is referring to when it says:

> Use read() to read inputs, and write() to write to outputs

If it's not for creating more specific functions for things attached to pins, what are they referring to?

**Comment by joshgoebel** [comment]
> If it's not for creating more specific functions for things attached to pins, what are they referring to?

It's for writing to pins.  They couldn't name it any differently because they don't KNOW what you are attaching.  If you're attaching a printer you might want to print... if you're attaching a gun you might want to shoot... the higher level the function the higher level the concept.  Your api would be print("Bob") or shoot(5)... look at some of the other Arduino libraries, not just the guide.

if you're selling someone a board with 20 switches they might all say "switch one", "switch two", but someone is going to write "fridge", "washer", "drier" on the switches, and they'd be insane not to. :)

**Comment by joshgoebel** [comment]
Look at the mouse api for example.  You don't write mouse status to USB, you `click` and `move` and `press` and `release` things.  The functions match the function.

I think you missed the very top of the guide:

> Be kind to the end user. Assume you are writing an API for an intelligent person who has not programmed before. Come up with a clear mental model of the concept you’re working with, and the terms and functions you will use.

There are things you write and read, and then they are things you shoot, click, launch, boot, process, etc... and sometimes if you're at a higher level you are setting things, not writing them... search the entire Arduino source for set.*( and you'll find plenty of set, including setTX and setRX for one example, for setting those pins.

**Comment by MLXXXp** [comment]
_writeRGBled()_ or _writeRGBcolor()_ read as clearly to me as _setRGBled()_ or _setRGBcolor_. (Except, being Canadian, I would keep entering _colour_ and have to go back and correct it to _color_ :wink:)

Actually, thinking further, _writeRGBcolor()_ (or _set_) is a bit vague. RGB alone doesn't really describe a specific object. If you're going to include _color_ in the function name, it should also indicate that it's an LED, such as _setRGBledColor()_. So I'd just use _setRGBled()_ without _color_. Besides, we're actually setting intensity as well as color. (We might even want to overload the function, at a later date, to allow [HSV or HSL](https://en.wikipedia.org/wiki/List_of_color_spaces_and_their_uses#Hue_and_saturation), or something else.)

From a user standpoint, I don't look at it as being three separate LEDs in one package. I see it as a single point of light that can be set to many colors and intensities, like a pixel on a display. So just like I _write_ to a RAM location, I'm writing to a pixel or other light source.

Anyway, I personally don't care whether you use _set_ or _write_, or prefix or postfix, or separate functions instead of boolean arguments, I was just pointing out what it says in the guide (at least, my interpretation). To me, _set_ and _write_ are synonymous, as are _get_ and _read_. I've had no problem understanding any of them and all would be fine by me.

**Comment by MLXXXp** [comment]
> It's for writing to pins. They couldn't name it any differently because they don't KNOW what you are attaching.

The could have named them _setDigitalPin()_, _getDigitalPinState()_, _setAnalogOutput()_, _getAnalogInput()_. :wink:

OK, I'll shut up now :smile:

**Comment by joshgoebel** [comment]
As I said they use set\* in plenty of other places... it's all contextual.

**Comment by joshgoebel** [comment]
@rogosher Any thoughts on:

```
 ledTXon(); 
 ledRXoff();
```

**Comment by MLXXXp** [comment]
> Any thoughts on:
>  ledTXon(); 
>  ledRXoff();

If the _TXLED0_, _TXLED1_, _RXLED0_, _RXLED1_ macros are kept in the the Arduboy version of _pins_arduino.h_, they will do same thing. @yyyc514, I know that you don't like this kind of obfuscation, but they're already documented and accepted by the Arduino community, so I don't have a problem with just using them directly.

Then again, adding the functions doesn't hurt, and they're a bit clearer than the macros. They won't add to code size if they're not used.

Personally I would prefer single functions (regardless of the actual name) with a boolean on/off parameter, regardless of if you interpret the style guide as not recommending them.

``` cpp
void setRXled(boolean on);
void setTXled(boolean on);
```

They can be used to force the LED to a specific state as easily as two separate functions, but it makes it a bit easier to restore a previously saved state:

``` cpp
setRXled(savedLEDstate);
```

instead of

``` cpp
savedLEDstate ? ledRXon() : ledRXoff();

// or more likely for a programmer unfamiliar with using the conditional expression:
if (savedLEDstate == ON) {
  ledRXon();
} else {
  ledRXoff();
}
```

**Comment by joshgoebel** [comment]
I'll think about it more. One advantage of functions (other than being easy to find in the Api docs) is that if you use them a few times they start to save you flash space. Those defines just get added to your code over and over again. 

Not sure why arduino itself doesn't provide a helper for this. Maybe it assumes using the LEDs for serious stuff someone would know all this and act accordingly?

**Comment by MLXXXp** [comment]
> Not sure why arduino itself doesn't provide a helper for this.

Because the TX and RX LEDs were put there mainly to provide USB communication status. Their use for other purposes isn't common, and possibly not even encouraged.

**Comment by joshgoebel** [comment]
Except we are really custom hardware - and they have no purpose at all when not connected to USB. But I guess I see why they didn't encourage going crazy with them. I could see going either way on this.

**Comment by joshgoebel** [comment]
OK, I'm in in the air now - does anyone else have an opinion on whether the TX/RX should be included?

**Comment by MLXXXp** [comment]
It doesn't matter much to me if they're included or not, but as I've already said, if you **do** add them, I'd prefer two functions that accept a boolean argument instead of four separate _on_ only or _off_ only functions

**Comment by joshgoebel** [comment]
I think I'm going to side with Arduino for now.  These are hardware LEDs for TX/RX and if someone wants to use them it's also easy enough to use the provided defines.
