### ISSUE TITLE
rename getInput() to buttonsState()

### ISSUE THREAD

**Issue by joshgoebel** [Arduboy/Arduboy#78]
Or pollButtonState()?  pollButtonStatus()? getInput is too generic and makes me write library code like:

```
uint8_t button_state = getInput();
if (button_state & LEFT_BUTTON)
```

I do that because to me getInput is opaque and I want clarity.  What input exactly am I getting?  But then I realized the real problem is the name of the method, it could be more descriptive.

Not many should use this directly but we should still have the best name possible

**Comment by joshgoebel** [comment]
```
readButtonState() // ?
readButtons() // ?
```

I could imagine read used here.

**Comment by MLXXXp** [comment]
Like I said in PR #23, I kind of like just `buttonState()`.

It certainly works with:

``` cpp
boolean Arduboy::pressed(uint8_t buttons)
{
  return (buttonState() & buttons) == buttons;
}
```

and pretty much every other use I can think of.

You can't write to buttons, so _read_ is implied.

**Comment by joshgoebel** [comment]
The word state is very programmery, but so is poll.  Condition is silly though.  Is there  much better word I'm not thinking of?

**Comment by MLXXXp** [comment]
> The word state is very programmery

I don't know if I agree about that. _State_ has pretty much the same meaning outside of programming. E.g. "_State of the Union_", "_In a confused state_". So, I think _buttonState_ is fairly descriptive. Even the Doxygen comments for _getInput_ currently begin with:
`// get current state of buttons (bitmask)`

And @yyyc514, you yourself used `button_state = getInput()` when you wrote function _pressed()_.

Besides, people using the function **will** be programmers, or if they're "programmers in training" they should be expected to become familiar with the meaning of _state_ in this context.

I agree that _condition_ doesn't sound right. The only other I can think of  is _buttonPositions()_, which I'm not too keen on.

It's maybe a bit more descriptive to use the plural _buttonsState()_, but that reads kind of strange.

**Comment by joshgoebel** [comment]
`buttonsState()`  I like.  It's clear that it's polling multiple buttons (not just returning one) and again this is low-level and people using it should understand what it does.

**Comment by MLXXXp** [comment]
> `buttonsState()` I like

That's fine with me then. :smile:
