### ISSUE TITLE
audio.save_on_off() should be audio.saveOnOff()

### ISSUE THREAD

**Issue by MLXXXp** [Arduboy/Arduboy#80]
Another underscore to camelCase change to comply with Arduino library guidelines. Does this one need to be deprecated?

I can created a pull request if desired.

**Comment by joshgoebel** [comment]
It's fairly new, and I'm not aware people are using it yet so could probably get away without deprecation.

**Comment by MLXXXp** [comment]
Pull request #83 created. Closing.
