### ISSUE TITLE
Shipped game included in examples

### ISSUE THREAD

**Issue by MLXXXp** [Arduboy/Arduboy#90]
What game is the production Arduboy shipping with?

I think it would be a good idea to have this game included in the library examples. After a user loads something else, they may want go back to the default game. Having it as an example makes it easy to find and re-load.

**Comment by shogerr** [comment]
That is a good question. Part of me thinks it might be one of JO3RI's.

**Comment by MLXXXp** [comment]
Even if it is JO3RI's, if it's the default game shipped with the Arduboy, then it should be maintained as part of the Arduboy source.

**Comment by shogerr** [comment]
I agree.

**Comment by ghost** [comment]
https://github.com/TEAMarg/ID-28-Blob-Attack

**Comment by joshgoebel** [comment]
> then it should be maintained as part of the Arduboy source.

I don't see where that is a requirement if it's already on Github and separate maintained - link to it - that's what the web is for.

**Comment by shogerr** [comment]
This is beyond the scope of the Arduboy library.
