### ISSUE TITLE
ab_logo.h shouldn't  be included in sketches

### ISSUE THREAD

**Issue by MLXXXp** [Arduboy/Arduboy#94]
When a developer uses _Sketch -> Include Library -> Arduboy_ from the IDE menus, `#include <ab_logo.h>` is added to the sketch (along with `#include <Arduboy.h>`). This header shouldn't be included in a sketch.

The reason _ab_logo_ is included is because the IDE includes all _.h_ files residing directly in the _src_ directory.
Possible ways to fix this:
- Move _ab_logo.h_ to a subdirectory under _src/_ (such as _bitmaps_) and in _Arduboy.cpp_ change `#include "ab_logo.h"` to `#include "bitmaps/ab_logo.h"`
- Change _ab_logo.h_ to _ab_logo.c_, as _glcdfont.c_ is. Why is one a _.h_ file and one a _.c_ file anyway? They both do the same thing, so should have the same extension. The library should be consistent.

Note that if we decide that _glcdfont.c_ should be _glcdfont.h_, it should be moved to a subdirectory under _src/_ as well, for the same reason. It can be the same directory that we put _ab_logo.h_ in.

**Comment by shogerr** [comment]
I do like moving from a header tile to a source file, as I don't see this file as being something many people will change the source for, and it's a small bit of source.

**Comment by MLXXXp** [comment]
So should _glcdfont.c_ be changed to _glcdfont.h_?

Is _bitmaps_ a good name for the directory to put both files in?

**EDIT**: Sorry, I read "I do not like" when you wrote "I do like". Disregard this comment.

**Comment by joshgoebel** [comment]
One difference is C files are going to be auto compiled and .h files are not, but since both of these files only add a variable that is either referenced or unreferenced I don't think it should really matter to the compiler... so I think them both being .c wouldn't necessarily be harmful... but I really don't know the "proper" C opinion on this.  It seems in most of the source I find/read that large amounts of data/images/etc are put in the headers.

I think we should find out and then either rename both, or make both .h.

I preset `assets` or `resources`.  Bitmaps is too specific.

**Comment by joshgoebel** [comment]
If we're still getting carried away with dirs maybe put the font in `fonts`. :-)  I'd love to see us ship a non ugly font, but no time to work on it.

**Comment by yyyc514** [comment]
I'd love to see us ship a non ugly font, but no time to work on it.

**Comment by MLXXXp** [comment]
> I don't think it should really matter to the compiler... so I think them both being .c wouldn't necessarily be harmful... but I really don't know the "proper" C opinion on this.

It's obviously not harmful, since it works for _glcdfont.c_.

My personal rule is to never put anything in a header file that actually generates code or sets values in storage. A _.h_ file should be used to define prototypes or templates for things, not actually create things. I would have used a _.c_ or _.cpp_ file. I found a few references on the Web that agree with this. I didn't see any that said a _.h_ file should be used.

Changing _ab_logo.h_ to _ab_logo.c_ would mean we wouldn't have to move it to a subdirectory.

**Comment by shogerr** [comment]
I agree with the notion of a header being used explicitly for definitions. C++ really doesn't ever want you to put source in a header file; a project's source should always be in a source file with some special exceptions. That's pretty [cut and dry in the C++ world](http://stackoverflow.com/questions/583255/c-code-in-header-files).

So go towards `.c` files for the logo and font source.

I do like that idea of a less specific folder, `assets` or `resources` do seem to fit better than `bitmap`. If a goal is to reduce the folder count going forward then a more abstract folder name could catch "resources" or "assets" created in the future. But these nouns do suggest some sort of binary like an image. `helpers`, `utility`? Not sure in this moment.

**Comment by MLXXXp** [comment]
> I do like that idea of a less specific folder, assets or resources do seem to fit better than bitmap.

Like I've said, if we are going to change _ab_logo.h_ to _ab_logo.c_, then _ab_logo.c_ and _glcdfont.c_ can both remain directly in the _src_ directory without any issues. Therefore, there's no need to decide on a name or create a new subdirectory at this time.

**Comment by shogerr** [comment]
Cool beans, time for my nap ; ) We still might toss around a name for that eventual case. I vote `util` now : P

**Comment by MLXXXp** [comment]
PR #98 created.
